# Generated by Django 5.0.1 on 2024-02-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('topic', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('opt1', models.CharField(max_length=2)),
                ('opt2', models.CharField(max_length=2)),
                ('opt3', models.CharField(max_length=2)),
                ('opt4', models.CharField(max_length=2)),
            ],
        ),
    ]
