# Generated by Django 5.0.1 on 2024-02-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_opt1_answers_que1_rename_opt2_answers_que2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='submission',
            field=models.BooleanField(default=False),
        ),
    ]
