# Generated by Django 5.0.1 on 2024-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_answers_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='submission',
        ),
        migrations.AddField(
            model_name='answers',
            name='prgrscontribution',
            field=models.FloatField(default='0.0'),
        ),
    ]
