# Generated by Django 5.0.1 on 2024-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='streak',
        ),
        migrations.AddField(
            model_name='profile',
            name='progress',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
