# Generated by Django 5.0.1 on 2024-02-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0003_remove_profile_streak_profile_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='progress',
        ),
        migrations.AddField(
            model_name='profile',
            name='c1progress',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='c2progress',
            field=models.FloatField(default='0'),
        ),
    ]
