# Generated by Django 5.0.1 on 2024-02-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0004_remove_profile_progress_profile_c1progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imguploadlimit',
            field=models.PositiveSmallIntegerField(default='10'),
        ),
    ]
