# Generated by Django 5.0.1 on 2024-04-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0005_profile_imguploadlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hackerrank_id',
            field=models.CharField(default='yourhackerrankid', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='yournickname', max_length=30),
        ),
    ]
